"""add view_count to posts and bio to users

Revision ID: 4fe68f3914c8
Revises: 6c597ca80e1c
Create Date: 2026-07-26 12:59:01.169778

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4fe68f3914c8'
down_revision: str | Sequence[str] | None = '6c597ca80e1c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'posts',
        sa.Column('view_count', sa.Integer(), nullable=False, server_default='0'),
    )
    op.add_column('users', sa.Column('bio', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bio')
    op.drop_column('posts', 'view_count')
    # ### end Alembic commands ###
